version: '3'
services:
  app:
    image: syaifuddinzuhri/docker-laravel-app:latest
    container_name: app
    restart: unless-stopped
    tty: true
    env_file: .env
    depends_on:
      - cache
    networks:
      - app-network

  web_server:
    image: syaifuddinzuhri/docker-laravel-app-web_server:latest
    container_name: web_server
    restart: unless-stopped
    tty: true
    ports:
      - "8003:80"
    depends_on:
      - app
    networks:
      - app-network

  cache:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
